require("dotenv").config();
const db = require("../db");
const fs = require("fs");
const bcrypt = require("bcryptjs");
const { randomUUID } = require('crypto'); // Import for generating IDs

(async () => {
  try {
    // 1. Create Categories Table
    await db.query(`
      CREATE TABLE IF NOT EXISTS categories (
        id TEXT PRIMARY KEY, -- Using TEXT to store the UUID generated by randomUUID()
        name TEXT UNIQUE NOT NULL
      );
    `);
    console.log("✅ Categories table ensured.");

    // 2. Ensure Products Table exists (updated to use TEXT for ID for router consistency)
    // NOTE: If this table already exists with SERIAL, changing to TEXT here might cause issues.
    // For a safe migration, we'll keep the user's original definition, but add missing columns.
    await db.query(`
      CREATE TABLE IF NOT EXISTS products (
        id TEXT PRIMARY KEY, -- Changed from SERIAL for compatibility with router's randomUUID()
        product_code TEXT UNIQUE, -- Added product_code (missing but used in router)
        name TEXT NOT NULL,
        brand_name TEXT NOT NULL,
        buying_price INTEGER NOT NULL,
        selling_price INTEGER NOT NULL,
        vendor_price INTEGER NOT NULL,
        quantity INTEGER NOT NULL,
        date DATE NOT NULL,
        images JSONB,
        is_top_selling BOOLEAN DEFAULT false,
        is_featured BOOLEAN DEFAULT false,
        is_budget_friendly BOOLEAN DEFAULT false,
        custom_fields JSONB,
        description TEXT
      );
    `);

    await db.query(`
      CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'vendor',
        refresh_token TEXT
      );
    `);

    // 3. Add missing columns to Products table (Migrations)
    await db.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS description TEXT;
    `);
    await db.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS product_code TEXT UNIQUE;
    `);
    await db.query(`
      ALTER TABLE products
      ADD COLUMN IF NOT EXISTS category_id TEXT REFERENCES categories(id); -- Add foreign key
    `);
    console.log("✅ Products table migrations complete.");

    // 4. Seed Categories
    const defaultCategories = [
      { name: "Electronics", id: randomUUID() },
      { name: "Home Goods", id: randomUUID() },
      { name: "Apparel", id: randomUUID() },
      { name: "Books", id: randomUUID() }
    ];

    for (const cat of defaultCategories) {
      const exists = await db.query(`SELECT id FROM categories WHERE id=$1`, [cat.id]);
      if (exists.rows.length === 0) {
        await db.query(
          `INSERT INTO categories (id, name) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING`,
          [cat.id, cat.name]
        );
        console.log(`Inserted category: ${cat.name}`);
      } else {
         console.log(`Skipped existing category: ${cat.name}`);
      }
    }
    console.log("✅ Categories seed complete.");
    const categoryIds = defaultCategories.map(c => c.id);

    // 5. Seed products
    const raw = fs.readFileSync("./data/products.json", "utf8");
    const products = JSON.parse(raw);

    for (const p of products) {
      // Assign a random category ID from the seeded list
      const randomCategoryIndex = Math.floor(Math.random() * categoryIds.length);
      const categoryId = categoryIds[randomCategoryIndex];
      
      // Ensure product code exists (use p.id as basis or generate new UUID if needed)
      const productCode = p.productCode || randomUUID();
      
      const q = `
        INSERT INTO products
          (id, name, brand_name, buying_price, selling_price, vendor_price, 
           quantity, date, images, is_top_selling, is_featured, is_budget_friendly, 
           custom_fields, description, product_code, category_id)
        VALUES
          ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
        ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          product_code = EXCLUDED.product_code,
          category_id = EXCLUDED.category_id -- Update category on conflict
      `;

      const values = [
        String(p.id), // Ensure ID is a string/text type for consistency
        p.name,
        p.brandName,
        p.buyingPrice,
        p.sellingPrice,
        p.vendorPrice,
        p.quantity,
        p.date,
        JSON.stringify(p.images || []),
        p.isTopSelling || false,
        p.isFeatured || false,
        p.isBudgetFriendly || false,
        JSON.stringify(p.customFields || []),
        p.description || null,
        productCode, // Value for $15
        categoryId // Value for $16
      ];

      await db.query(q, values);
      console.log(`Inserted/Updated product ${p.id} - ${p.name}`);
    }

    console.log("✅ Products seed complete.");

    // 6. Seed default users
    const defaultUsers = [
      { email: "admin@example.com", password: "admin123", role: "admin" },
      { email: "vendor1@example.com", password: "vendor123", role: "vendor" }
    ];

    for (const u of defaultUsers) {
      const exists = await db.query(`SELECT id FROM users WHERE email=$1`, [u.email]);
      if (exists.rows.length === 0) {
        const hashedPassword = await bcrypt.hash(u.password, 10);
        await db.query(
          `INSERT INTO users (email, password, role) VALUES ($1, $2, $3)`,
          [u.email, hashedPassword, u.role]
        );
        console.log(`Inserted user ${u.email} (${u.role})`);
      } else {
        console.log(`Skipped existing user ${u.email}`);
      }
    }

    console.log("✅ Users seed complete.");
    process.exit(0);

  } catch (err) {
    console.error("❌ Seed error", err);
    process.exit(1);
  }
})();